backend:
  name: github
  repo: joetheproz5/le-kiosk-menu # Ensure this is your exact repo name
  branch: main

media_folder: "menupictures"
public_folder: "menupictures"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "data/menu"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "desc", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["Appetizers", "Sandwiches", "Burgers", "Desserts"]}
      - {label: "Image", name: "image", widget: "image"}
